from typing import Protocol, List

from app.domain.entities.book import BookEntity


class BookServiceProtocol(Protocol):
    def get_all_books(self) -> List[BookEntity] | None: ...

    def get_book_by_id(self, book_id: int) -> BookEntity: ...

    def filter_books(self, **filters) -> List[BookEntity] | None: ...

    def add_book(self, book_add_data: dict) -> BookEntity: ...

    def update_book(self, book_id: int, book_update_data: dict) -> BookEntity: ...

    def delete_book(self, book_id) -> None: ...
